### PR TITLE
fix: take gitsigns config from inner module

### PR DESCRIPTION
**Pull request by marcelbeumer**
Fixing regression after https://github.com/folke/zen-mode.nvim/commit/21ca264c6ae934ceac220cf719c0ed6c0216b057#diff-79fe7b2f00da5c112ea6be1547972b941947fc4444103e14bc9f9548de1f8875L5

### CODE REVIEW

**Comment by folke** [comment]
This doesn't seem correct?

It should be `require("gitsigns.config").config` as it is right now. Am I missing something?

**Comment by folke** [comment]
`require("gitsigns").config` does not exist, so would definitely fail

**Comment by folke** [comment]
Nevermind 🤦‍♂️

Thank you for fixing this :)

**Comment by marcelbeumer** [comment]
zen-mode w/ gitsigns still worked for me yesterday or so, much later than your last commit, I think gitsigns made changes

**Comment by marcelbeumer** [comment]
probably falsely accused regression on your side, sorry 😇

**Comment by folke** [comment]
I totally misread your diff. I probably need to get some sleep 😅

**Pull request merged**
